"""fixing database structure

Revision ID: 16e742bda7c8
Revises: 1e1ca71d6275
Create Date: 2025-06-25 18:47:07.800806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e742bda7c8'
down_revision: Union[str, Sequence[str], None] = '1e1ca71d6275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('customers', sa.Column('store_name', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('tax_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'customers', ['tax_id'])
    op.alter_column('products', 'unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_constraint(op.f('products_store_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'store_id')
    op.drop_table('stores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_store_id_fkey'), 'products', 'stores', ['store_id'], ['store_id'])
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.alter_column('products', 'unit_price',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'tax_id')
    op.drop_column('customers', 'store_name')
    op.create_table('stores',
    sa.Column('store_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tax_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('store_id', name=op.f('stores_pkey')),
    sa.UniqueConstraint('store_name', name=op.f('stores_store_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tax_id', name=op.f('stores_tax_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
