"""dropping sales table to fix primary key

Revision ID: 207d5aaaf2c7
Revises: fb674a119401
Create Date: 2025-07-01 21:31:49.993053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207d5aaaf2c7'
down_revision: Union[str, Sequence[str], None] = 'fb674a119401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')    
    op.drop_constraint(op.f('invoices_customer_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['customer_id'])
    op.drop_table('sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_customer_id_fkey'), 'invoices', 'sales', ['customer_id'], ['customer_id'])
    op.create_table('sales',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sale_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('sales_customer_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('sales_product_id_fkey')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('sales_pkey'))
    )
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    # ### end Alembic commands ###
