"""removing invoice_id form sales

Revision ID: 25adcc14c26a
Revises: bb8d6dbf7d5a
Create Date: 2025-07-02 17:07:31.117328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25adcc14c26a'
down_revision: Union[str, Sequence[str], None] = 'bb8d6dbf7d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sales_invoice_id_fkey'), 'sales', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('sales_invoice_id_fkey'), 'sales', 'invoices', ['invoice_id'], ['invoice_id'])
    # ### end Alembic commands ###
