"""Model fix

Revision ID: 40f8643a0356
Revises: b0a4ce586944
Create Date: 2025-06-30 12:23:52.497937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f8643a0356'
down_revision: Union[str, Sequence[str], None] = 'b0a4ce586944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sale_id', sa.BigInteger(), nullable=False))
    op.alter_column('sales', 'customer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.alter_column('sales', 'customer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('sales', 'sale_id')
    # ### end Alembic commands ###
