"""fixing sales

Revision ID: 75ca611a079a
Revises: 25adcc14c26a
Create Date: 2025-07-02 17:16:25.494430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ca611a079a'
down_revision: Union[str, Sequence[str], None] = '25adcc14c26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
