"""adjusting models for invoices

Revision ID: bb8d6dbf7d5a
Revises: d7cac6611bec
Create Date: 2025-07-02 16:17:53.158695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8d6dbf7d5a'
down_revision: Union[str, Sequence[str], None] = 'd7cac6611bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('invoices_sale_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['customer_id'])
    op.drop_column('invoices', 'sale_id')
    op.drop_column('invoices', 'quantity')
    op.drop_column('invoices', 'total_amount')
    op.add_column('sales', sa.Column('invoice_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sales', 'invoices', ['invoice_id'], ['invoice_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'invoice_id')
    op.add_column('invoices', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_sale_id_fkey'), 'invoices', 'sales', ['sale_id'], ['sale_id'])
    op.drop_column('invoices', 'customer_id')
    # ### end Alembic commands ###
