"""adding users table for role based authentication

Revision ID: d7cac6611bec
Revises: 3973b9b90872
Create Date: 2025-07-02 11:18:23.518473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7cac6611bec'
down_revision: Union[str, Sequence[str], None] = '3973b9b90872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_admin_admin_id'), 'admin', ['admin_id'], unique=False)
    op.create_foreign_key(None, 'admin', 'users', ['user_id'], ['user_id'])
    op.add_column('customers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.create_index(op.f('ix_sales_sale_id'), 'sales', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_sale_id'), table_name='sales')
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_column('customers', 'user_id')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_index(op.f('ix_admin_admin_id'), table_name='admin')
    op.drop_column('admin', 'user_id')
    # ### end Alembic commands ###
