"""adding quantity to sales

Revision ID: e856c346d3e8
Revises: 75ca611a079a
Create Date: 2025-07-02 17:37:20.064109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e856c346d3e8'
down_revision: Union[str, Sequence[str], None] = '75ca611a079a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_column('sales', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sales', 'quantity')
    # ### end Alembic commands ###
