"""Update customer to sales

Revision ID: f84089d9aa81
Revises: 16e742bda7c8
Create Date: 2025-06-27 13:41:50.036026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84089d9aa81'
down_revision: Union[str, Sequence[str], None] = '16e742bda7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.drop_index(op.f('ix_customer_product_id'), table_name='customer')
    op.drop_table('customer')
    op.add_column('products', sa.Column('tax_percent', sa.Numeric(precision=3, scale=2), nullable=False))
    op.drop_column('products', 'tax%')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tax%', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
    op.drop_column('products', 'tax_percent')
    op.create_table('customer',
    sa.Column('customer_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('customer_product_id_fkey')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('customer_pkey'))
    )
    op.create_index(op.f('ix_customer_product_id'), 'customer', ['product_id'], unique=False)
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
