"""adjusting numeric values and default of orm models

Revision ID: fb674a119401
Revises: 40f8643a0356
Create Date: 2025-06-30 16:40:39.249631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb674a119401'
down_revision: Union[str, Sequence[str], None] = '40f8643a0356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'unit_price',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'tax_percent',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'tax_percent',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'unit_price',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
