"""adding password for customer

Revision ID: fb8fe2d109ac
Revises: f84089d9aa81
Create Date: 2025-06-29 19:20:55.406969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8fe2d109ac'
down_revision: Union[str, Sequence[str], None] = 'f84089d9aa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'password')
    # ### end Alembic commands ###
